### ISSUE TITLE
Latest 0.2 release doesn't include Ben Manu's umask commit

### ISSUE THREAD

**Issue by con-steve** [silverstripe-labs/silverstripe-testsession#23]
Means that when I run composer update it doesn't include this code:

https://github.com/silverstripe-labs/silverstripe-testsession/commit/c526d481e127d51b9dcd8b8da579131071cea800

End result is that when I run behat via console using firefox webdriver on my imac I get permission errors

**Comment by chillu** [comment]
sweet, I've created 0.2.1 - https://github.com/silverstripe-labs/silverstripe-testsession/releases/tag/0.2.1
